name: LinuxBuild

on:
  push:
      branches: [ main ]
        pull_request:
            branches: [ main ]
              workflow_dispatch:
              jobs:
                buildLinux:
                    runs-on: ubuntu-latest
                        steps:
                              - uses: actions/checkout@v2
                              
                                    - uses: krdlab/setup-haxe@master
                                            with:
                                                      haxe-version: 4.2.5
                                                            - name: Install Haxelib
                                                                    run: |
                                                                              sudo apt-get install libvlc-dev
                                                                                        sudo apt-get install libvlccore-dev
                                                                                                  haxelib setup ~/haxelib
                                                                                                            haxelib install hxcpp > /dev/null --quiet
                                                                                                            
                                                                                                                      # TYPE THE HAXELIB DEPENDENCIES HERE.
                                                                                                                      
                                                                                                                            - name: Create Version Tag
                                                                                                                                    run: echo "${{github.run_id}}" > VERSION
                                                                                                                                          - name: Compile
                                                                                                                                                  run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
                                                                                                                                                        - name: Publish Artifact
                                                                                                                                                                uses: actions/upload-artifact@v2.2.4
                                                                                                                                                                        with:
                                                                                                                                                                                  name: linuxBuild
                                                                                                                                                                                            path: 'export/release/linux/bin'
                                                                                                                                                                                            
